### ISSUE TITLE
Migrate "Delete Site" site to /edit-site

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/worona-dashboard#104]
- [ ] After deleting the site we have to redirect the user to `/sites`

> **Work going on in this branch:** [deletesite-migration](https://github.com/worona/worona-dashboard/tree/deletesite-migration)

**Comment by Poliuk** [comment]
@luisherranz I'm having problems getting the SiteName & the SiteId from the State 😅

**Comment by luisherranz** [comment]
Solved.
