### ISSUE TITLE
unexpected "worona_plugin_not_found"

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/worona-dashboard#127]
The affected site is site: http://black-eagle.ml/

The endpoint is working correctly: http://black-eagle.ml/?rest_route=/worona/v1/siteid

But the dashboard is returning `WORONA_PLUGIN_NOT_FOUND`

**Comment by luisherranz** [comment]
This is the same redirect issue we've seen before to avoid CORS bypass. Instead of the JSON response the server returns:
```
<html>
    <body>
        <script type="text/javascript" src="/aes.js" ></script>
        <script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f
            <d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("982111b5c662281a856585287cdd96ae");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://black-eagle.ml/?rest_route=/worona/v1/siteid&i=1";
            </script>
            <noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript>
        </body>
    </html>
```
Then it adds a cookie and refreshes the page.

**Comment by Poliuk** [comment]
New case:

*Affected site* http://www.nouvelangle.media/?rest_route=/worona/v1/siteid
Customer email: lfourcade@nouvelangle.media

**Comment by luisherranz** [comment]
Although it seems valid, http://www.nouvelangle.media/ doesn't return a proper response: status is missing. It looks like without a proper status header, `cors-everywhere` fails.

**Comment by Poliuk** [comment]
Another issue:

https://backend.worona.io/api/v1/cors/http://mspdevotion.org/?rest_route=/worona/v1/siteid

&

http://mspdevotion.org/?rest_route=/worona/v1/siteid

Are giving different answers.

> customer email: napa.onwusah@shuzia.com
