### ISSUE TITLE
Worona phyton not found

### ISSUE THREAD

**Issue by neroshin** [wp-pwa/worona-dashboard#138]
hello I am newbie here , I got some error from compiling the project in cmd it said "phyton not found" somebody here can solve it?

**Comment by Poliuk** [comment]
Hello @neroshin where are you getting that error?

**Comment by neroshin** [comment]
I run in powershell , should it need a phyton?

**Comment by Poliuk** [comment]
Hello again @neroshin, are you following our documentation?  https://docs.worona.org/dashboard/publish/do-it-yourself.html

You don't need to compile anything on your computer. You have to use Phonegap build instead.

**Comment by neroshin** [comment]
I'm getting cofused @Poliuk ,how can I use the worona dashboard open source , It should be run in phonegap?

**Comment by luisherranz** [comment]
@neroshin you don't need to install it on your servers, you can just use our online dashboard. It's free :)

If you have more doubts about his please send us an email to support@worona.org.
