### ISSUE TITLE
Close Worona

### ISSUE THREAD

**Issue by orballo** [wp-pwa/worona-dashboard#141]
- [x] Remove register link from `/login`.
- [x] Redirect `/register` to `/login`.
- [x] Remove Add Site button from `/sites`.
- [x] Redirect `/add-site` to `/sites`.
- [x] Remove Buy Now buttons from Choose Theme and Manage Extensions.
- [x] Disable Get It Now button from Publish (remove link also).
- [x] Add a Bulma.css message component (yellow) in `/sites`: "Important announcement: Worona’s platform and services will not be available after October 20, 2018 -> Learn more", with a link to `https://www.worona.org/important-service-announcement`
- [x] Add this same component to `/site`.

**Comment by Poliuk** [comment]
omg the day has come 😢

**Comment by orballo** [comment]
Worona is dead, long live The Company Formerly Known As Worona!
