### ISSUE TITLE
Adapt the new Login and Register design.

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/worona-dashboard#22]
https://github.com/worona/worona-dashboard-layout/blob/master/sites/login.html
https://github.com/worona/worona-dashboard-layout/blob/master/sites/register.html

**Comment by Poliuk** [comment]
Related issue: https://github.com/worona/worona-dashboard/issues/19

**Comment by Akronix** [comment]
@Poliuk They're still missing a place for server errors and server status messages.

**Comment by Poliuk** [comment]
@Akronix added:
[login error](https://worona.github.io/worona-dashboard-layout/sites/login-error.html#)
[register error](https://worona.github.io/worona-dashboard-layout/sites/register-error.html#)

**Comment by Poliuk** [comment]
Status messages added as well:

[login status](https://worona.github.io/worona-dashboard-layout/sites/login-status.html#)
[register status](https://worona.github.io/worona-dashboard-layout/sites/register-status.html#)
