### ISSUE TITLE
"Add Site" should check if Rest API & Worona Plugin are activated

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/worona-dashboard#30]
The "Add Site" page has to check if the WordPress site has:
- The REST API activated
- The Worona Plugin activated (The Worona plugin has to register and endpoint in the REST API).
- A Worona Site ID generated in the WordPress site.
### Checklist

![checklist](https://cloud.githubusercontent.com/assets/2798729/18841932/ad8b7a22-8413-11e6-98a0-f7736ddf1ccb.png)
### Why?

There will be users following the next onboarding:
1. User lands in [worona.org](https://www.worona.org)
2. User clicks a CTA
3. User registers in [dashboard.worona.org/register](https://dashboard.worona.org/register)
4. User adds site 
5. ????

Once user has reached step 4, it doesn't make sense to make him install the Worona WP Plugin, because everything is already working. In addition, it can be confusing to "Create an App ID" from the Worona WordPress Plugin if he has previously added the site to the dashboard.

Worona Dashboard can work if the WP Site has the REST API installed, but it is important to us to increase Worona Plugin installs in the Plugin Directory.

**Comment by Poliuk** [comment]
The workflow has to be redesigned, the proposal doesn't work.

In any case, the Worona WordPress Plugin and SiteID can be discovered using the rest API ([worona-wp-plugin #2](https://github.com/worona/worona-wp-plugin/issues/2) &  [worona-wp-plugin #1](https://github.com/worona/worona-wp-plugin/issues/1)). This will make easier the "add site" from the dashboard.

**Comment by Akronix** [comment]
Splitted in #39, #40, #41, #42 and #43
