### ISSUE TITLE
Missing AsideMenu in SiteHome on Mobile.

### ISSUE THREAD

**Issue by Akronix** [wp-pwa/worona-dashboard#38]
On Mobile, there's no navigation menu for selecting the site settings:
![photo_2016-10-03_13-31-02](https://cloud.githubusercontent.com/assets/2631430/19036036/afae1dd2-896d-11e6-9774-ba2010bbadc9.jpg)

It should be done like in [here](https://worona.github.io/worona-dashboard-layout/sites/site/site.html).

**Comment by Poliuk** [comment]
@Akronix why the status is blocked instead of bug?

**Comment by Akronix** [comment]
It's blocked because I'm waiting for @luisherranz to fix the config site (SiteHome) screen.

**Comment by luisherranz** [comment]
I'll unblockit when it's ready.

**Comment by Poliuk** [comment]
@Akronix perfect, I was asking just in case you needed me to design the menu.

**Comment by Akronix** [comment]
@Poliuk I think what you did already it's fine. We can take a look further when I'm coding this.

**Comment by Poliuk** [comment]
@Akronix you can adapt the lateral menu to mobile resolutions. The code is [here](https://worona.github.io/worona-dashboard-layout/sites/site/mobile-menu.html).

**Comment by Akronix** [comment]
Now this is in `components/SiteHome/MobileMenu` but the desktop menu version is in `elements/AsideMenu`.
We should consider a more consistent "path layout".
