### ISSUE TITLE
Error screen when adding site fails any check

### ISSUE THREAD

**Issue by Akronix** [wp-pwa/worona-dashboard#43]
An screen to tell the user what check failed and how to fix it.

When this screen should appear:
1. Site responds 404 / 500
2. No rest API on given siteURL
3. No worona in REST API
4. Already existing siteID found in target site.

In the first three cases, the site will be created in the dashboard, but this screen will be prompted anytime the user tries to configure that site.

In the last case, the site will be created in the dashboard as well and the user can enter in the SiteHome (configure link), but he won't be able to publish the app (see #41 )

In every case, a warning icon will be displayed in the SitesList (see #39)

**Comment by Poliuk** [comment]
@Akronix Here are the different animations for each case:

### Everything is OK

[checks](https://worona.github.io/worona-dashboard-layout/sites/site/checks.html) -> [checks-1](https://worona.github.io/worona-dashboard-layout/sites/site/checks-1.html) -> [checks-2](https://worona.github.io/worona-dashboard-layout/sites/site/checks-2.html) -> [checks-3](https://worona.github.io/worona-dashboard-layout/sites/site/checks-3.html) -> [checks-4](https://worona.github.io/worona-dashboard-layout/sites/site/checks-4.html) -> [redirect](https://worona.github.io/worona-dashboard-layout/sites/site/site.html)

### WordPress Plugin not installed (Blocking error)

[checks](https://worona.github.io/worona-dashboard-layout/sites/site/checks.html) -> [checks-1](https://worona.github.io/worona-dashboard-layout/sites/site/checks-1.html) -> [checks-2](https://worona.github.io/worona-dashboard-layout/sites/site/checks-2.html) -> [checks-error](https://worona.github.io/worona-dashboard-layout/sites/site/checks-error.html)

### SiteIds not matching (Warning - nonblocking)

[checks](https://worona.github.io/worona-dashboard-layout/sites/site/checks.html) -> [checks-1](https://worona.github.io/worona-dashboard-layout/sites/site/checks-1.html) -> [checks-2](https://worona.github.io/worona-dashboard-layout/sites/site/checks-2.html) -> [checks-3](https://worona.github.io/worona-dashboard-layout/sites/site/checks-3.html) -> [checks-warning](https://worona.github.io/worona-dashboard-layout/sites/site/checks-warning.html)

Retry button should switch to `is-loading` and trigger the check again.

**Comment by Poliuk** [comment]
Error messages are missing. 

[Site Online error](https://worona.github.io/worona-dashboard-layout/sites/site/checks-error.html)
[Worona Plugin error](https://worona.github.io/worona-dashboard-layout/sites/site/checks-error-2.html)

Related issue: [worona-dashboard-layout/issues/15](https://github.com/worona/worona-dashboard-layout/issues/15)
