### ISSUE TITLE
Send Mixpanel notifications based on check-site status for every site

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/worona-dashboard#49]
We are going to use [mixpanel](www.mixpanel.com) to send automatic notifications (emails) depending on events. There's a set of notifications related with the checksite process, we want to be able to send an automatic email with help instructions when a user adds a site and check site triggers an error.

We're gonna start preparing the system to handle only 5 active sites. This means that Mixpanel will have the following notifications configured:

![screen shot 2016-10-18 at 14 09 58](https://cloud.githubusercontent.com/assets/2798729/19477063/bfee5dc6-953c-11e6-9bac-1dd4ae935787.png)
- **Site_1 plugin not installed**
- **Site_2 plugin not installed**
- **Site_3 plugin not installed**
- **Site_4 plugin not installed**
- **Site_5 plugin not installed**

The same with the other errors:
- **Site_X not online**

_We will close this issue once the notifications are configured in mixpanel. This issue is blocked until the dashboard handles the [site_X assignation (#50)](https://github.com/worona/worona-dashboard/issues/50), and it sends info to populate events in mixpanel_

**Comment by Poliuk** [comment]
This first approach doesn't work well with our database model, because a site can have different users. 

We've sent an email to mixpanel to see if they have a pattern to handle this kind of scenarios.

**Comment by Poliuk** [comment]
Mixpanel answer:

> Notifications within Mixpanel can be sent based on both events and people properties.  Here is a great article on sending your first notification: http://bit.ly/2ef2h9P.  For more specific details on different types of notifications, check out the Notification section on the left.
> 
> For this specific example, I would recommend setting both a super property and people property to designate the error 1, error 2, error 3, or ready.  To do this, you will want to define a property, like "state," and set it as either error1, error 2, error 3, or ready.  This would allow you to identify users both by people properties and the super property of specific events in order to send notifications.  Since super properties are defined at the time an event occurs, you can send targeted notifications based on the time an event is sent, while people properties would allow you to send notifications based on the property's current state.  For more information on super properties and people properties, check out this helpful link: http://bit.ly/2cJEgab.
> 
> With a property set as "state," you would then be able to create a notification for each state: 1,2,3, ready.  You would then be able to set a specific time during the day at which to send the notifications, or ASAP so that they receive the notification as soon as they are in one of these states.  Regardless of the number of apps created, the people property will always show the most recent update to the property "state," so this will represent the state of their most recent app.  If you later decide you want to target people who were in a certain state in the past, you could then utilize a specific event and filter it based on the specific state for which you are looking.  
> 
> One issue worth bringing up here is that a notification campaign will automatically exclude those who have already received the notification.  In other words, if a user receives a notification from each different notification campaign for error 1, error 2, error 3, and ready during the creation of their first app, they will be excluded from receiving those notifications on all future apps.  So this would only work during the creation of a user's first app.  For more information on this limitation, and how to ensure you are saving the right information in order to send notifications, check out this helpful Mixpanel article: http://bit.ly/2efcTp5.
> 
> I hope this helps, have a great day!

**Comment by Poliuk** [comment]
_(Still blocked, I've insisted to them in order to find a solution to our issue)_

> Thanks for your prompt reply. At the end of the email you are pointing out the issue I don't know how to solve.
> 
> Every user can create unlimited apps, each app will have the 3 error states mentioned above. I want to send a notification to the user when any of its apps is in an error state.
> 
> If the user A, creates 10 Apps, and 3 of them are in error 1 state, he has to get 3 different emails. 
> 
> Is there a way in mixpanel to monitor a collection of entities that belong to a user?
> 
> Hope I've explained the issue in a better way now.

**Comment by Poliuk** [comment]
Final answer:

> In order to ensure that Mixpanel does not spam users, the only way in which to send a notification twice is to create another notification campaign.  One potential way in which to get around this would be to set a different people property for each app created, then set the property as error 1, error 2, error 3, ready.  In this case, you would still need to create a separate campaign to target each step of each app.  Alternatively, you could use Mixpanel to identify the users you would like to send a notification, then use Webhooks in order to send them from a separate notification service.  Here is a link on using Webhooks within Mixpanel: http://bit.ly/2diAVvD.
> 
> Have a great day!

**Comment by luisherranz** [comment]
We need to ask about webhooks, to see if they are triggered only once.

**Comment by Poliuk** [comment]
@luisherranz just got their reply... Webhooks are triggered only once as well

> Unfortunately, Mixpanel notifications are designed to only send a user a notification one time.  For this reason, you would have to create separate campaigns for each notification as previously stated, even if you did use Webhooks.  
> 
> This could be a lot of work to set up, so I would recommend using another service, such as MailChimp, that would allow you to send an email multiple times.  You could still use your Mixpanel data in order to target specific users by exporting, transforming, and sending it to another service.  Here is our Mixpanel blog post on exporting your data: http://bit.ly/2e4ODCR

**Comment by luisherranz** [comment]
Ok. Maybe it's not that bad.

**Comment by Poliuk** [comment]
finally done 👍

**Comment by luisherranz** [comment]
🙌
