### ISSUE TITLE
Load of core (site) packages

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/worona-dashboard#6]
- General
- Excludes
- Publish
- Change theme
- Add extensions

**Comment by Akronix** [comment]
- [x] General -> Done here: https://github.com/worona/general-app-extension-worona
- [x] Publish -> Repo here: https://github.com/worona/publish-native-app-extension-worona, just [one issue](https://github.com/worona/publish-native-app-extension-worona/issues/1) and some extra testing left.
~~Change theme -> Not done, need to be done before launch?~~
- [x] Add extensions -> Done here: https://github.com/worona/extensions-manager-app-extension-worona
- [x] (extra) Starter theme -> Done in https://github.com/worona/starter-app-theme-worona

**Comment by Poliuk** [comment]
Change Theme is not RFL.

**Comment by Poliuk** [comment]
We have to discuss about "exludes" as I think they are deeply linked to the app URL routing system

**Comment by luisherranz** [comment]
We can discuss it tomorrow.

**Comment by luisherranz** [comment]
Everything added.
