### ISSUE TITLE
Change Site Name & Site URL screen

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/worona-dashboard#60]
Related Issue > [dashboard-layout #10](https://github.com/worona/worona-dashboard-layout/issues/10)

**Comment by Poliuk** [comment]
The new screen will be accessed from the cogs favicon next to the site name in the hero.
![screen shot 2016-10-20 at 20 54 12](https://cloud.githubusercontent.com/assets/2798729/19573668/8241c81a-9707-11e6-8e87-78b2691386a6.png)

The new screen [/edit-site](https://worona.github.io/worona-dashboard-layout/sites/edit-site-disabled.html) uses the same layout and elements from [/add-site](https://worona.github.io/worona-dashboard-layout/sites/add-site.html)

Note: Buttons in `/edit-site` are disabled until user inputs something.
[disabled](https://worona.github.io/worona-dashboard-layout/sites/edit-site-disabled.html) -> [active](https://worona.github.io/worona-dashboard-layout/sites/edit-site.html)

**Comment by luisherranz** [comment]
In my opinion name first and URL second feels more natural.
