### ISSUE TITLE
Remove "Check Site id" from /check-site

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/worona-dashboard#61]
Check site will have only two checks. 

The site id will be checked only when entering /publish-webapp (rel. issue #62)

**Comment by Poliuk** [comment]
Modified in layout https://github.com/worona/worona-dashboard-layout/issues/11

**Comment by Akronix** [comment]
and what about displaying a 3rd check in case that user has WordPress API but hasn't Worona WP Plugin?

**Comment by Poliuk** [comment]
We have decided to force everybody to install our WordPress Plugin for marketing purposes. That's why the second check directly checks for the worona-wp-plugin instead of the REST API and blocks the user until it installs the plugin.
