### ISSUE TITLE
Generate zip file for phonegap build (publish package)

### ISSUE THREAD

**Issue by Akronix** [wp-pwa/worona-dashboard#71]
- [x] Icons and splash screens. Related issue #68 
- [x] generate zip file packaging everything above.
- [x] config.xml
- [x] Phonegap plugins 
- [x] add worona site id to config.xml

**Comment by luisherranz** [comment]
Plugin to access config.xml
https://www.npmjs.com/package/cordova-plugin-appsettings

**Comment by Poliuk** [comment]
Inside config.xml file, the id field `id = "com.phonegap.example"` will be generated using the `siteURL` as explained in the example below:

```
www.site.com -> id = "com.site.www.app"

www.site.com/directory -> id = "com.site.www.directory.app"

www.site.com/directory/subdirectory -> id = "com.site.www.directory.subdirectory.app"
```

**Comment by Poliuk** [comment]
Just finished with the Imgix params #68
