### ISSUE TITLE
Create "maintenance" page

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/worona-dashboard#72]
Follow this tutorial to create a "maintenance" page redirection in NGINX.
https://www.calazan.com/how-to-configure-nginx-so-you-can-quickly-put-your-website-into-maintenance-mode/

Then create a node script to switch (rename) from that mode, and add it to the npm scripts.

**Comment by Akronix** [comment]
I read the docs, and I can accomplish this but I need a designed html page. @Poliuk , could you do it?

**Comment by luisherranz** [comment]
I think this is not needed before launch. It's not that important.

**Comment by luisherranz** [comment]
Not really needed ATM.
