### ISSUE TITLE
A package shouldn't be able to edit other package settings

### ISSUE THREAD

**Issue by Akronix** [wp-pwa/worona-dashboard#74]
Currently any package can edit, save and even erase settings for other packages without any security prevention in between.

Maybe, somehow, every package should receive actions intended for that package only.

**Comment by luisherranz** [comment]
I agree, but due to the complexity of the implementation and the fact that we are going to control all the code from packages for a while, it's not needed for the launch.

**Comment by luisherranz** [comment]
Won't fix.
