### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by Akronix** [wp-pwa/worona-dashboard#80]
Update to new Worona logo.

**Comment by Poliuk** [comment]
Done in dashboard-layout: https://github.com/worona/worona-dashboard-layout/issues/24

**Comment by luisherranz** [comment]
The logo is not retina ready, it needs to be 2x the resolution with a fixed width and height in the code.

**Comment by luisherranz** [comment]
Or svg...

**Comment by Poliuk** [comment]
Changed in https://github.com/worona/worona-dashboard-layout/issues/24 @Akronix

**Comment by luisherranz** [comment]
Awesome. Looks great now 👍
