### ISSUE TITLE
To add a modal to confirm the deletion of a site

### ISSUE THREAD

**Issue by Akronix** [wp-pwa/worona-dashboard#83]
- [ ] Cancel button or clicking outside the modal should close it.
- [ ] In the header `AppName` must display the name of the App that is about to be deleted 

**Design available here:** [sites-modal-delete.html](https://worona.github.io/worona-dashboard-layout/sites/sites-modal-delete.html)

> Documentation [bulma modals](http://bulma.io/documentation/components/modal/)

Second part of #57

**Comment by Poliuk** [comment]
If you need, I can design this in dashboard layout. Just let me know 👍🏼

**Comment by Akronix** [comment]
related design: https://github.com/worona/worona-dashboard-layout/issues/25

**Comment by Poliuk** [comment]
Cancel button and clicking outside the modal should close it. (removing the `is-active` class)

> Documentation [bulma modals](http://bulma.io/documentation/components/modal/)

**Comment by Poliuk** [comment]
**Design available here:** [sites-modal-delete.html](https://worona.github.io/worona-dashboard-layout/sites/sites-modal-delete.html)

**Comment by luisherranz** [comment]
There is a typo in the text:

*Your app will stop working and you will **lose** your preferences*

**Comment by luisherranz** [comment]
I've fixed it myself, don't worry 😄  https://github.com/worona/worona-dashboard-layout/commit/2846c8f631c40fc56bfa784553c6ad2ed71d2255

**Comment by Poliuk** [comment]
Thanks @luisherranz 😅
