### ISSUE TITLE
Slight changes to the publish text

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/worona-dashboard#85]
> But keep in mind that you will also need a Google and an Apple developer account, which costs more than $130 combined.

We should add that it's 130€ combined and **then 100€ per year.**

> If you choose our Worona Publish Service you won’t have to worry about not having a developer account or the compilation process. 

Double negation. I think it should be "you won’t have to worry about having a developer account"

**Comment by luisherranz** [comment]
@rmartinezduque could you please take a look?

**Comment by Akronix** [comment]
Actually, the repo with that text involved is this one:
https://github.com/worona/publish-native-app-extension-worona

**Comment by rmartinezduque** [comment]
Done

**Comment by luisherranz** [comment]
Thanks @rmartinezduque!
