### ISSUE TITLE
Menu labels doesn't match with dashboard layout

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/worona-dashboard#90]
- [ ] `General > General Settings` should be `Settings > General`
- [x] `Themes > Config Starter Theme` should be `Themes > Starter Theme` (https://github.com/worona/starter-app-theme-worona/issues/3)
- [x] `Themes` should be above `Extensions`

### Layout

![screen shot 2017-01-11 at 12 26 14](https://cloud.githubusercontent.com/assets/2798729/21846831/2f7ddc80-d7f9-11e6-8f9f-a56e261bb9d1.png)

### Dashboard

![screen shot 2017-01-11 at 12 27 04](https://cloud.githubusercontent.com/assets/2798729/21846853/4bd62d92-d7f9-11e6-8ba6-da8167a1abee.png)

**Comment by Poliuk** [comment]
- `General > General Settings` should be `Settings > General`
 is still missing

**Comment by luisherranz** [comment]
It's not deployed yet, but it's fixed.
